export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU';
export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU';
export const SET_TAB_TITLE = 'SET_TAB_TITLE';
export const SET_INFINITY_LIST_SETTINGS = 'SET_INFINITY_LIST_SETTINGS';